HBMS/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('adminmodule.urls')),
    path('manager/',include('managermodule.urls')),
    path('customer/',include('customermodule.urls')),



]

managermodule/urls.py
from django.contrib import admin
from django.urls import path,include

from . import views
app_name = 'managermodule'

urlpatterns = [
    path('addrooms/',views.addrooms,name='addrooms'),
    path('add_room_details/',views.add_room_details,name='add_room_details'),
    path('view/',views.view_roomdetails,name='view_roomdetails'),
    path('insert/', views.insert_emp, name='insert-emp'),
    path('show/', views.show_emp, name='show-emp'),
    path('edit/<int:pk>', views.edit_emp, name='edit-emp'),
    path('remove/<int:pk>', views.remove_emp, name='remove-emp'),




]

templates/navbar/customernavbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg" style="background-color:#66ff66;">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'homepage' %}">HBMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'homepage' %}">Home</a>
        </li>
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'viewrooms' %}">view rooms</a>
        </li>


           <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'review_list' %}">Reviews</a>
        </li>
          <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'topdestinations' %}">topdestinations</a>
        </li>

      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>

         <ul class = "navbar-nav ms-auto">
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'managerhomepage' %}">Manager</a>
              </li>
             <li class="nav-item">
                  <a class="nav-link" href="{% url 'customerhomepage' %}">Customer</a>
              </li>
         </ul>


        <ul  class="navbar-nav ms-auto">
<li>
        {% if user.is_authenticated %}
        <li class="nav-item">
        <span class="nav-link">Welcome, {{ user.username }}</span>
    </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
        {% else %}
                <li class="nav-item">
          <a class="nav-link" href="{% url 'signup' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
        {% endif %}



      </ul>
    </div>
  </div>

</nav>

{% block body %}

{% endblock %}
</body>
</html>

templates/navbar/managernavbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg" style="background-color:#ff471a;">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'homepage' %}">HBMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'homepage' %}">Home</a>
        </li>
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'managermodule:addrooms' %}">Add Rooms</a>
        </li>
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'managermodule:view_roomdetails' %}">View Rooms</a>
        </li>

          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
              <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
         <ul class = "navbar-nav ms-auto">
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'managerhomepage' %}">Manager</a>
              </li>
             <li class="nav-item">
                  <a class="nav-link" href="{% url 'customerhomepage' %}">Customer</a>
              </li>
         </ul>






        <ul  class="navbar-nav ms-auto">
<li>
        {% if user.is_authenticated %}
        <li class="nav-item">
        <span class="nav-link">Welcome, {{ user.username }}</span>
    </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
        {% else %}
                <li class="nav-item">
          <a class="nav-link" href="{% url 'signup' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
        {% endif %}




      </ul>
    </div>
  </div>
</nav>

{% block body %}

{% endblock %}
</body>
</html>

templates/navbar/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg" style="background-color: #40E0D0 ">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'homepage' %}">HBMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'homepage' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'aboutus' %}">About Us</a>
        </li>
      </ul>
        <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
         <ul class = "navbar-nav ms-auto">
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'managerhomepage' %}">Manager</a>
              </li>
             <li class="nav-item">
                  <a class="nav-link" href="{% url 'customerhomepage' %}">Customer</a>
              </li>
         </ul>




        <ul  class="navbar-nav ms-auto">
<li>
        {% if user.is_authenticated %}
        <li class="nav-item">
        <span class="nav-link">Welcome, {{ user.username }}</span>
    </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
        {% else %}
                <li class="nav-item">
          <a class="nav-link" href="{% url 'signup' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
        {% endif %}

 </li>

      </ul>
    </div>
  </div>
</nav>
{% block body %}

{% endblock %}
<footer id ="sticky-footer" class="flex-shrink-0 py-2">
    <div class = "container text-center">
        <small> Copyright Divyasri - KL University. All rights reserved</small>
    </div>
</footer>
<style>
    #sticky-footer {
    position: fixed;
    bottom: 0;
    left: 0;
    right: 0;
    background-color: #EBDEF0;
    color: black;
    padding: 10px;
    font-weight: bold;



</style>
</body>
</html>